name: boarding_kiosk
channels:
  - pypi

dependencies:
  - python=3.9
  - flask
  - pip
  - msrest
  - pip:
    - azure-core
    - azure-common
    - azure-storage-blob
    - azure-ai-formrecognizer
    - azure-cognitiveservices-vision-computervision
    - azure-cognitiveservices-vision-customvision
    - azure-cognitiveservices-vision-face
    - video-indexer
    - python-dotenv